spring:
  application:
    name: gateway-svc

  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      excludedURLsNew: /auth/login

server:
  port: ${port:8889}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: department
        url: /v3/api-docs/department
      - name: employee
        url: /v3/api-docs/employee
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

debug: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
